#include "sam.h"

/**
	@brief Configure System Clocks
	@details Configures clocks for a SAMD11
*/
void init_Clocks(void)
{
	// _pm_init
	PM_REGS->PM_CPUSEL= PM_CPUSEL_CPUDIV_DIV1;
	PM_REGS->PM_APBASEL = PM_APBASEL_APBADIV_DIV1;
	PM_REGS->PM_APBBSEL = PM_APBBSEL_APBBDIV_DIV1;
	PM_REGS->PM_APBCSEL = PM_APBCSEL_APBCDIV_DIV1;
	
	// _sysctrl_init_sources
	SYSCTRL_REGS->SYSCTRL_OSC8M = ((SYSCTRL_REGS->SYSCTRL_OSC8M & SYSCTRL_OSC8M_FRANGE_Msk) |
	(SYSCTRL_REGS->SYSCTRL_OSC8M & SYSCTRL_OSC8M_CALIB_Msk) |
	SYSCTRL_OSC8M_PRESC_0 | SYSCTRL_OSC8M_ENABLE(1));
	SYSCTRL_REGS->SYSCTRL_OSC32K |= (SYSCTRL_OSC32K_ENABLE(1) | SYSCTRL_OSC32K_EN32K(1));
	//SYSCTRL->OSCULP32K.reg |= ((SYSCTRL->OSCULP32K.reg & SYSCTRL_OSCULP32K_CALIB_Msk) Not sure why it does this?
	while((SYSCTRL_REGS->SYSCTRL_PCLKSR & SYSCTRL_PCLKSR_OSC8MRDY(1))==0);
	SYSCTRL_REGS->SYSCTRL_OSC8M |= SYSCTRL_OSC8M_ONDEMAND(1);
	
	// _sysctrl init referenced
	SYSCTRL_REGS->SYSCTRL_DFLLCTRL = SYSCTRL_DFLLCTRL_ENABLE(1);
	while((SYSCTRL_REGS->SYSCTRL_PCLKSR & SYSCTRL_PCLKSR_DFLLRDY(1)) == 0);
	SYSCTRL_REGS->SYSCTRL_DFLLMUL = (SYSCTRL_DFLLMUL_CSTEP(1) | SYSCTRL_DFLLMUL_FSTEP(1) | SYSCTRL_DFLLMUL_MUL(48000));
	//uint32_t CoarseCALRead =  ((SYSCTRL_DFLLVAL_COARSE_Msk & (*((uint32_t *)FUSES_DFLL48M_COARSE_CAL_ADDR))) >> SYSCTRL_DFLLVAL_COARSE_Pos);
	//SYSCTRL_REGS->SYSCTRL_DFLLVAL =  SYSCTRL_DFLLVAL_COARSE(((CoarseCALRead) == 0x3F) ? 0x1F : (CoarseCALRead)) | SYSCTRL_DFLLVAL_FINE(512);
	SYSCTRL_REGS->SYSCTRL_DFLLCTRL = (SYSCTRL_DFLLCTRL_CCDIS(1) | SYSCTRL_DFLLCTRL_USBCRM(1) | SYSCTRL_DFLLCTRL_MODE(1) | SYSCTRL_DFLLCTRL_ENABLE(1));
	while((SYSCTRL_REGS->SYSCTRL_PCLKSR & SYSCTRL_PCLKSR_DFLLRDY(1)) == 0);
	while(GCLK_REGS->GCLK_STATUS & GCLK_STATUS_SYNCBUSY(1));
	//SYSCTRL->OSC32K.reg &= (~SYSCTRL_OSC32K_ENABLE);
	
	// _gclk_init_generators last init
	GCLK_REGS->GCLK_GENDIV = (GCLK_GENDIV_DIV(1) | GCLK_GENDIV_ID(0));
	GCLK_REGS->GCLK_GENCTRL = (GCLK_GENCTRL_GENEN(1) | GCLK_GENCTRL_SRC_OSC8M | GCLK_GENCTRL_ID(0));
	GCLK_REGS->GCLK_GENDIV = (GCLK_GENDIV_DIV(1) | GCLK_GENDIV_ID(1));
	GCLK_REGS->GCLK_GENCTRL = (GCLK_GENCTRL_GENEN(1) | GCLK_GENCTRL_SRC_DFLL48M | GCLK_GENCTRL_ID(1));
	GCLK_REGS->GCLK_GENDIV = (GCLK_GENDIV_DIV(1) | GCLK_GENDIV_ID(3));
	GCLK_REGS->GCLK_GENCTRL = (GCLK_GENCTRL_GENEN(1) | GCLK_GENCTRL_SRC_OSC32K | GCLK_GENCTRL_ID(3));
	
	// enable PM and clkctrl
	PM_REGS->PM_APBBMASK |= (PM_APBBMASK_USB(1) | PM_APBBMASK_NVMCTRL(1));
	PM_REGS->PM_AHBMASK |= (PM_AHBMASK_USB(1) | PM_AHBMASK_NVMCTRL(1));
	GCLK_REGS->GCLK_CLKCTRL = (GCLK_CLKCTRL_ID(GCLK_CLKCTRL_ID_USB_Val) | GCLK_CLKCTRL_GEN(GCLK_CLKCTRL_GEN_GCLK1_Val) 
		| GCLK_CLKCTRL_CLKEN(1));
}

void init_IO(void)
{
	// OnboardLED - PA16
	PORT_REGS->GROUP[0].PORT_DIRSET = PORT_DIRSET_DIRSET(1u<<16);
	PORT_REGS->GROUP[0].PORT_OUTCLR = PORT_OUTCLR_OUTCLR(1u<<16);
}

int main(void)
{
	init_Clocks();
	init_IO();

	for(;;){}
}